gameObject:
name: PlayerCharacter
active : true
components :
    Transform :
        position :
            x : 0.0
            y : 1.0
            z : 0.0
        rotation :
            x : 0.0
            y : 0.0
            z : 0.0
        scale :
            x : 1.0
            y : 1.0
            z : 1.0
    Renderer :
        mesh : PlayerMesh
        material : PlayerMaterial
        Collider :
            type: Box
            size :
                x: 1.0
                y : 2.0
                z : 1.0
            isTrigger : false
Script :
    name : PlayerController
    properties :
    speed: 5.0
    jumpHeight : 2.0
    health : 100
